Lessons Learned implemented:  import.php
    Had to install HTTP/Request, just as described in: http://stackoverflow.com/questions/4483317/failed-opening-required-http-request2-php-include-path-c-php5-pear
        pear install http_request2
        apt-get ... pear install 
    Error: Ung�ltige Buchart int.Verrechnung 

construct.php

    Construct queries did not find observations. Had to change the select query: ?obs rdf:type qb:Observation.
        Passte nur bei BudgetPlanung: qb:dataSet?ds.?ds qb:structure smwcube:dsd. 
    Had to update the prefixes from Sesame.
    Had to query for observations, simply.